class InvalidUser(Exception): pass
class BadUploadType(Exception): pass
class BadTransactionType(Exception): pass
class BadDateInput(Exception): pass
class NullDateInput(Exception): pass
class MissingHeader(Exception): pass
class NullReturnType(Exception): pass
class BadReturnType(Exception): pass
class BadUploadData(Exception): pass